
import Header from "@/components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        {/* add "dark" class to body to change theme to Dark theme */}
      <Header/>
        {children}
      </body>
    </html>
  );
}
